version: "3.2"

services:
  db:
    image: postgres
    container_name: "soundbit_postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soundbit_dev
    ports:
      - 5432:5432
